.git
.idea
designs
designs/**

data
data/**
tmp
tmp/**
components-font-awesome
components-font-awesome/**

config.yml
*.local.yml

originpulse
originpulse.exe
data/originpulse-dev.exe
*.tmp
*.log
originpulse-*.log
